// This file is generated by autd_wrapper_generator

using System;
using System.Runtime.InteropServices;
using System.Text;

namespace AUTD3Sharp
{
    internal static unsafe class NativeMethods
    {
        private const string DllName = "autd3capi";

        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern void AUTDCreateController(out IntPtr @out);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern int AUTDOpenControllerWith(IntPtr handle, IntPtr pLink);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern int AUTDAddDevice(IntPtr handle, float x, float y, float z, float rz1, float ry, float rz2, int groupId);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern int AUTDAddDeviceQuaternion(IntPtr handle, float x, float y, float z, float quaW, float quaX, float quaY, float quaZ, int groupId);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] [return: MarshalAs(UnmanagedType.U1)] public static extern bool AUTDCalibrate(IntPtr handle, int smplFreq, int bufSize);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern void AUTDCloseController(IntPtr handle);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern void AUTDClear(IntPtr handle);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern void AUTDFreeController(IntPtr handle);
        [DllImport(DllName, CharSet = CharSet.Ansi, BestFitMapping = false, ThrowOnUnmappableChar = true, CallingConvention = CallingConvention.StdCall)] public static extern void AUTDSetSilentMode(IntPtr handle, [MarshalAs(UnmanagedType.U1)] bool mode);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern void AUTDStop(IntPtr handle);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern int AUTDGetAdapterPointer(out IntPtr @out);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern void AUTDGetAdapter(IntPtr pAdapter, int index, StringBuilder desc, StringBuilder name);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern void AUTDFreeAdapterPointer(IntPtr pAdapter);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern int AUTDGetFirmwareInfoListPointer(IntPtr handle, out IntPtr @out);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern void AUTDGetFirmwareInfo(IntPtr pFirmInfoList, int index, StringBuilder cpuVer, StringBuilder fpgaVer);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern void AUTDFreeFirmwareInfoListPointer(IntPtr pFirmInfoList);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] [return: MarshalAs(UnmanagedType.U1)] public static extern bool AUTDIsOpen(IntPtr handle);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] [return: MarshalAs(UnmanagedType.U1)] public static extern bool AUTDIsSilentMode(IntPtr handle);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern float AUTDWavelength(IntPtr handle);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern void AUTDSetWavelength(IntPtr handle, float wavelength);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern void AUTDSetDelay(IntPtr handle, ushort* delay, int dataLength);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern int AUTDNumDevices(IntPtr handle);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern int AUTDNumTransducers(IntPtr handle);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern ulong AUTDRemainingInBuffer(IntPtr handle);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern void AUTDFocalPointGain(out IntPtr gain, float x, float y, float z, byte duty);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern void AUTDGroupedGain(out IntPtr gain, int* groupIds, IntPtr* inGains, int size);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern void AUTDBesselBeamGain(out IntPtr gain, float x, float y, float z, float nX, float nY, float nZ, float thetaZ, byte duty);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern void AUTDPlaneWaveGain(out IntPtr gain, float nX, float nY, float nZ, byte duty);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern void AUTDCustomGain(out IntPtr gain, ushort* data, int dataLength);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern void AUTDHoloGain(out IntPtr gain, float* points, float* amps, int size, int method, IntPtr @params);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern void AUTDTransducerTestGain(out IntPtr gain, int idx, byte duty, byte phase);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern void AUTDNullGain(out IntPtr gain);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern void AUTDDeleteGain(IntPtr gain);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern void AUTDModulation(out IntPtr mod, byte amp);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern void AUTDCustomModulation(out IntPtr mod, byte* buf, uint size);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern void AUTDRawPCMModulation(out IntPtr mod, string filename, float samplingFreq);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern void AUTDSawModulation(out IntPtr mod, int freq);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern void AUTDSineModulation(out IntPtr mod, int freq, float amp, float offset);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern void AUTDSquareModulation(out IntPtr mod, int freq, byte low, byte high);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern void AUTDWavModulation(out IntPtr mod, string filename);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern void AUTDDeleteModulation(IntPtr mod);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern void AUTDSequence(out IntPtr @out);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern void AUTDSequenceAppendPoint(IntPtr seq, float x, float y, float z);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern void AUTDSequenceAppendPoints(IntPtr seq, float* points, ulong size);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern float AUTDSequenceSetFreq(IntPtr seq, float freq);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern float AUTDSequenceFreq(IntPtr seq);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern float AUTDSequenceSamplingFreq(IntPtr seq);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern ushort AUTDSequenceSamplingFreqDiv(IntPtr seq);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern void AUTDCircumSequence(out IntPtr @out, float x, float y, float z, float nx, float ny, float nz, float radius, ulong n);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern void AUTDDeleteSequence(IntPtr seq);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern void AUTDSOEMLink(out IntPtr @out, string ifname, int deviceNum);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern void AUTDTwinCATLink(out IntPtr @out, string ipv4Addr, string amsNetId);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern void AUTDLocalTwinCATLink(out IntPtr @out);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern void AUTDEmulatorLink(out IntPtr @out, string addr, ushort port, IntPtr handle);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern void AUTDAppendGain(IntPtr handle, IntPtr gain);
        [DllImport(DllName, CharSet = CharSet.Ansi, BestFitMapping = false, ThrowOnUnmappableChar = true, CallingConvention = CallingConvention.StdCall)] public static extern void AUTDAppendGainSync(IntPtr handle, IntPtr gain, [MarshalAs(UnmanagedType.U1)] bool waitForSend);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern void AUTDAppendModulation(IntPtr handle, IntPtr mod);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern void AUTDAppendModulationSync(IntPtr handle, IntPtr mod);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern void AUTDAppendSTMGain(IntPtr handle, IntPtr gain);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern void AUTDStartSTModulation(IntPtr handle, float freq);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern void AUTDStopSTModulation(IntPtr handle);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern void AUTDFinishSTModulation(IntPtr handle);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern void AUTDAppendSequence(IntPtr handle, IntPtr seq);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern void AUTDFlush(IntPtr handle);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern int AUTDDeviceIdxForTransIdx(IntPtr handle, int globalTransIdx);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern float* AUTDTransPositionByGlobal(IntPtr handle, int globalTransIdx);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern float* AUTDTransPositionByLocal(IntPtr handle, int deviceIdx, int localTransIdx);
        [DllImport(DllName, CallingConvention = CallingConvention.StdCall)] public static extern float* AUTDDeviceDirection(IntPtr handle, int deviceIdx);

    }
}
